### ISSUE TITLE
Django allauth logout

### ISSUE THREAD

**Issue by zyjswiadomielife** [raratiru/django-letsagree#36]
Hi, I try to create logout link with django allauth.

In settings I try:
LETSAGREE_LOGOUT_APP_NAME = 'account_logout'
LETSAGREE_LOGOUT_APP_NAME = 'allauth:account_logout'
LETSAGREE_LOGOUT_APP_NAME = reverse_lazy('allauth')
LETSAGREE_LOGOUT_APP_NAME = reverse_lazy('allauth:account_logout')

But non of this work. Always I see: 'account_logout' is not a registered namespace etc.

How to create correct link?

**Second question**

How to translate button and checkbox, I must to do this in template? Or somewhere else?

**Comment by raratiru** [comment]
Hallo,

> Hi, I try to create logout link with django allauth.

The "correct" setting would be:

`LETSAGREE_LOGOUT_APP_NAME = 'allauth'`

That, however will call:

 `reverse('allauth:logout')`...  which will do nothing because the correct path is `reverse('allauth:account_logout')`.

Thank you for the report, I will address this issue in the weekend!

> How to translate button and checkbox, I must to do this in template? Or somewhere else?

The idea for the translation is to use [`./manage.py makemessages`](https://docs.djangoproject.com/en/dev/ref/django-admin/#django-admin-makemessages), fill the relevant entries in the `.po` files and then [`./manage.py compilemessages`](https://docs.djangoproject.com/en/dev/ref/django-admin/#compilemessages) to apply the changes as per [the docs](https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#localization-how-to-create-language-files), have you tried it?

**Comment by zyjswiadomielife** [comment]
Thank you for response. :) 

I try this, to translate data, and wait for new update with repaired logout link. :)

**Comment by raratiru** [comment]
Version 1.1.2 is released, the working setting should be:

`LETSAGREE_LOGOUT_APP_NAME = 'allauth:account_logout'`

Is it working?

**Comment by zyjswiadomielife** [comment]
I try, but still: 'allauth' is not a registered namespace

From what I was looking for information in google, allauth don't have namespace. I use only "account_logout" to create link, without allauth:account_logout

**Comment by raratiru** [comment]
So, the correct use should be:

`reverse('account_logout')`

Will this work?

**Comment by zyjswiadomielife** [comment]
Django still search for namespace. 

This time when I try, and import reverse:
LETSAGREE_LOGOUT_APP_NAME = reverse('account_logout')

**Error appear:**
AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'

I try also:
LETSAGREE_LOGOUT_APP_NAME = reverse_lazy('account_logout')

and then error say:
'/accounts/logout/' is not a registered namespace

**Comment by raratiru** [comment]
Please update and try the following settings:

**DELETE** the setting: `LETSAGREE_LOGOUT_APP_NAME`
add the setting: `LETSAGREE_LOGOUT_URL = 'account_logout'`

**Comment by zyjswiadomielife** [comment]
Ok, update is pip install django-letsagree --upgrade yes?

Then delete LETSAGREE_LOGOUT_APP_NAME and add LETSAGREE_LOGOUT_URL = 'account_logout'

I don't see any error but, when show terms accept page in right top corner logout link is still /admin/logout/

I try also LETSAGREE_LOGOUT_URL = '/account/logout/'

Nothing change.

**Comment by raratiru** [comment]
```
$ pip freeze | grep letsagree
django-letsagree==1.1.4
```
The latest version is `1.1.4`.

Did you check with allauth that the correct name for the logout page is `account_logout`? In that setting you pass the string that will be included in the `reverse` command. The call is:

`reverse(settings.LETSAGREE_LOGOUT_URL)`.

I will also give a closer look in the afternoon to this part of the code that may always return 'admin:logout'.

https://github.com/raratiru/django-letsagree/blob/c754147bf9add170e2a03f0b3614bf26bb9e8da0/letsagree/views.py#L86-L92

**Comment by raratiru** [comment]
Version 1.1.5 is released, can you check now? Indeed there was a bug in the code.

**Comment by zyjswiadomielife** [comment]
Yes, now works 🥇 

Thanks for repair this. :)
