### ISSUE TITLE
Delete user don't work with letsagree

### ISSUE THREAD

**Issue by zyjswiadomielife** [raratiru/django-letsagree#56]
Hi, I try to delete user but then error show up: 

"Deleting a user will delete the objects that are associated with it. Unfortunately, you are not authorized to delete the following types of objects:"

Notary Public

I try this using admin account with full permissions. How to do this? I create test users in production, and now I need to delete it.

**Comment by raratiru** [comment]
https://github.com/raratiru/django-letsagree/blob/fe8f43761362c01a5e9b4cfa7c943b292c0fea37/letsagree/models.py#L65-L71

https://github.com/raratiru/django-letsagree/blob/fe8f43761362c01a5e9b4cfa7c943b292c0fea37/letsagree/admin.py#L72-L76

I have done it like a precaution thinking that a superuser can also use the command line in the serverl: `./manage.py shell`
